// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as service$0 from "../service/models.js";

export function DownloadSong(url: string, pathName: string): $CancellablePromise<void> {
    return $Call.ByID(2255307415, url, pathName);
}

export function GetAudioUrl(url: string): $CancellablePromise<string> {
    return $Call.ByID(3002826653, url);
}

export function GetSearchSuggestions(query: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(175097671, query);
}

export function GetTrayIconEnabled(): $CancellablePromise<boolean> {
    return $Call.ByID(3579970376);
}

export function SaveSongDialog(songName: string): $CancellablePromise<string> {
    return $Call.ByID(1500664818, songName);
}

export function SearchVideos(query: string): $CancellablePromise<service$0.VideoResult[] | null> {
    return $Call.ByID(3445286266, query);
}

export function SetTrayIconEnabled(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(2326685916, enabled);
}
