// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface VideoResult {
    "id": string;
    "title": string;
    "thumbnail": string;
    "url": string;
}
