// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseWindow() {
  return window['go']['handlers']['App']['CloseWindow']();
}

export function Shutdown(arg1) {
  return window['go']['handlers']['App']['Shutdown'](arg1);
}

export function StartServer() {
  return window['go']['handlers']['App']['StartServer']();
}
