// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';

export function CloseWindow():Promise<void>;

export function DownloadSong(arg1:string,arg2:string):Promise<void>;

export function GetAudioUrl(arg1:string):Promise<string>;

export function GetSearchSuggestions(arg1:string):Promise<Array<string>>;

export function GetTrayIconEnabled():Promise<boolean>;

export function SaveSongDialog(arg1:string):Promise<string>;

export function SearchVideos(arg1:string):Promise<Array<service.VideoResult>>;

export function SetTrayIconEnabled(arg1:boolean):Promise<boolean>;

export function StartTrayIfEnabled():Promise<void>;
