// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseWindow() {
  return window['go']['handlers']['Handler']['CloseWindow']();
}

export function DownloadSong(arg1, arg2) {
  return window['go']['handlers']['Handler']['DownloadSong'](arg1, arg2);
}

export function GetAudioUrl(arg1) {
  return window['go']['handlers']['Handler']['GetAudioUrl'](arg1);
}

export function GetSearchSuggestions(arg1) {
  return window['go']['handlers']['Handler']['GetSearchSuggestions'](arg1);
}

export function SaveSongDialog(arg1) {
  return window['go']['handlers']['Handler']['SaveSongDialog'](arg1);
}

export function SearchVideos(arg1) {
  return window['go']['handlers']['Handler']['SearchVideos'](arg1);
}

export function SetDiscordPresence(arg1, arg2) {
  return window['go']['handlers']['Handler']['SetDiscordPresence'](arg1, arg2);
}
